### ISSUE TITLE
[REQ] add HyMPS

### ISSUE THREAD

**Issue by forart** [BillyDM/awesome-audio-dsp#11]
Hi there, 
thanks for this interesting list !
We've added in the [Collections page](https://github.com/forart/HyMPS/blob/main/Audio/Collections.md#-) under the [AUDIO section](https://github.com/forart/HyMPS#-) of our [HyMPS project](https://www.forart.it/HyMPS) !

Please check it out and, if you like, please add it both in your [More lists page](https://github.com/BillyDM/awesome-audio-dsp/blob/main/sections/MORE_LISTS.md) and [Open Source Plugins & Software page](https://github.com/BillyDM/awesome-audio-dsp/blob/main/sections/OPEN_SOURCE_PLUGINS_AND_SOFTWARE.md#open-source-plugins--software) \ [More lists section](https://github.com/BillyDM/awesome-audio-dsp/blob/main/sections/OPEN_SOURCE_PLUGINS_AND_SOFTWARE.md#more-lists).

Thanks in advance !

**Comment by BillyDM** [comment]
Awesome, looks great! Added it in c9162d3e7e19d160ab5b49a0f4684f75202de0c9

**Comment by forart** [comment]
Thanks for the add.

If possible we ask you to use the official link to the project (https://www.forart.it/HyMPS) which correctly+transparently redirects to the repository and at the same time allows us to monitor how many peoples choose to visit it.

Thanks again.

**Comment by BillyDM** [comment]
Alright, updated the link in e50c968136ebcb7ef2853db59fdd5f5315f21443
